# Налаштування підключення до PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/paralel_lab_db
spring.datasource.username=postgres
spring.datasource.password=VBjf234Z!##

# Автоматичне створення та оновлення таблиць на основі твоїх моделей
spring.jpa.hibernate.ddl-auto=update

# Виведення SQL-запитів у консоль (дуже корисно для дебагу)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true